apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: http-server
  namespace: default
spec:
  serviceName: "http-server-service"
  replicas: 3
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
#      hostNetwork: true    # 直接使用宿主机网络（需处理端口冲突）
      containers:
      - name: http-server-container
        image: dockhub.ghtchina.com:6060/ims-cloud/http-server:latest
        imagePullPolicy: IfNotPresent
        command: ["stdbuf", "-oL", "/app/http_server"]
        ports:              # █ 新增：声明容器端口 █
        - containerPort: 8088
          name: http
          protocol: TCP
#        securityContext:
#          privileged: true

---
# █ 新增：创建 Service 暴露服务 █
apiVersion: v1
kind: Service
metadata:
  name: http-server-service
spec:
  type: NodePort          # 通过节点端口访问
  selector:
    app: http-server
  ports:
  - port: 8088            # Service 监听的端口
    targetPort: 8088      # 容器的端口
    nodePort: 30888       # 宿主机开放的端口（范围 30000-32767）
